### ISSUE TITLE
FROM statement pulls from parent

### ISSUE THREAD

**Issue by lucasgonze** [newrelic/newrelic-install-action#1]
# Summary

`Dockerfile` pulls this:

`FROM ghcr.io/julien4218/ansible-runner:main`

# Problem

That refers back to the parent of this repository before forking. It should be pulling from a newrelic-owned source. Pulling from a private account creates unauthorized access.

# Solution

Migrate`ghcr.io/julien4218/ansible-runner:main` to a newrelic-owned image. 

# Context

This repository was cloned into the organization from a parent created within a personal user account.

**Comment by Nandu-pns** [comment]
Hi @lucasgonze - Thank you for reporting the issue. This has been addressed as part of this [PR](https://github.com/newrelic/newrelic-install-action/pull/4/files).
